HOUSNAV-107: Change docker tag strategy (#59)

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -26,7 +26,7 @@ jobs:
     runs-on: ubuntu-latest
     environment: dev
     outputs:
-      short-commit-hash: ${{ steps.extract-commit-hash.outputs.short-git-sha }}
+      pr-number-output: ${{ steps.set-output.outputs.pr-number }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
@@ -34,32 +34,29 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
 
-      - name: Extract Git commit hash
-        id: extract-commit-hash
-        run: echo "short-git-sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
+      - name: Set PR number
+        id: set-pr-number
+        run: |
+          if [ -z "${{ github.event.number }}" ]; then
+            echo "PR number is empty. Failing workflow."
+            exit 1
+          else
+            echo "pr-number=${{ github.event.number }}" >> $GITHUB_OUTPUT
+          fi
+  
         
       - name: Build Docker image
-        run: docker build -t ${{ secrets.ARTIFACTORY_URL }}/${{ secrets.ARTIFACTORY_REPOSITORY_NAME }}/house-innovations-housnav-web:${{ steps.extract-commit-hash.outputs.short-git-sha }} -f apps/web/Dockerfile . --no-cache
+        run: docker build -t ${{ vars.ARTIFACTORY_URL }}/${{ secrets.ARTIFACTORY_REPOSITORY_NAME }}/house-innovations-housnav-web:${{ steps.set-pr-number.outputs.pr-number }} -f apps/web/Dockerfile . --no-cache
 
       - name: Login to Artifactory image registry with Docker
         uses: docker/login-action@v3
         with:
-          registry: ${{ secrets.ARTIFACTORY_URL }}
+          registry: ${{ vars.ARTIFACTORY_URL }}
           username: ${{ secrets.ARTIFACTORY_SERVICEACCOUNT_USERNAME }}
           password: ${{ secrets.ARTIFACTORY_SERVICEACCOUNT_PASSWORD }}
 
       - name: Push Docker image to Artifactory
-        run: docker push ${{ secrets.ARTIFACTORY_URL }}/${{ secrets.ARTIFACTORY_REPOSITORY_NAME }}/house-innovations-housnav-web:${{ steps.extract-commit-hash.outputs.short-git-sha }}
-
-      - name: Write Git commit hash to file
-        run: echo "${{ steps.extract-commit-hash.outputs.short-git-sha }}" > "outputs.txt"
-        
-      - name: Upload outputs to Artifactory
-        run: |
-          curl -v -X PUT \
-            --user ${{ secrets.ARTIFACTORY_SERVICEACCOUNT_USERNAME }}:${{ secrets.ARTIFACTORY_SERVICEACCOUNT_PASSWORD }} \
-            --upload-file ./outputs.txt \
-            https://${{ secrets.ARTIFACTORY_URL }}/artifactory/${{ secrets.ARTIFACTORY_REPOSITORY_NAME }}/outputs.txt
+        run: docker push ${{ vars.ARTIFACTORY_URL }}/${{ secrets.ARTIFACTORY_REPOSITORY_NAME }}/house-innovations-housnav-web:${{ steps.set-pr-number.outputs.pr-number }}
 
   cypress-run:
     needs: build
