Added manual trigger

diff --git a/.github/workflows/deploy-dev.yml b/.github/workflows/deploy-dev.yml
--- a/.github/workflows/deploy-dev.yml
+++ b/.github/workflows/deploy-dev.yml
@@ -7,6 +7,10 @@ on:
     paths-ignore:
       - '.github/**'
   workflow_dispatch:
+    inputs:
+      pr-number:
+        description: 'PR Number'
+        required: true
 
 jobs:
   build:
@@ -18,7 +22,19 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Extract pull request number associated with a commit
-        run: echo "PR_NUMBER=$(gh api /repos/bcgov/House-Innovations-HOUSNAV/commits/${{ github.sha }}/pulls | jq -r '.[0].number')" >> $GITHUB_ENV
+        id: extract-pr-number
+        run: |
+          if [ -z "${{ github.event.inputs.pr-number }}" ]; then
+            PR_NUMBER=$(gh api /repos/bcgov/House-Innovations-HOUSNAV/commits/${{ github.sha }}/pulls | jq -r '.[0].number')
+            if [ -z "$PR_NUMBER" ]; then
+              echo "PR number could not be extracted. Failing workflow."
+              exit 1
+            else
+              echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
+            fi
+          else
+            echo "PR_NUMBER=${{ github.event.inputs.pr-number }}" >> $GITHUB_ENV
+          fi
         env:
           GH_TOKEN: ${{ github.token }}
 
